In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
os.getcwd()

'C:\\Users\\sruja\\projectmini'

In [3]:
import os
os.chdir('C:\\Users\\sruja\\projectmini')

In [4]:
import pandas as pd

# Load a CSV file
df = pd.read_csv('full_df.csv')
df

,ID,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords,N,D,G,C,A,H,M,O,filepath,labels,target,filename
0,0,69,Female,0_left.jpg,0_right.jpg,cataract,normal fundus,0,0,0,1,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['N'],"[1, 0, 0, 0, 0, 0, 0, 0]",0_right.jpg
1,1,57,Male,1_left.jpg,1_right.jpg,normal fundus,normal fundus,1,0,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['N'],"[1, 0, 0, 0, 0, 0, 0, 0]",1_right.jpg
2,2,42,Male,2_left.jpg,2_right.jpg,laser spot，moderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,1,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",2_right.jpg
3,4,53,Male,4_left.jpg,4_right.jpg,macular epiretinal membrane,mild nonproliferative retinopathy,0,1,0,0,0,0,0,1,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4_right.jpg
4,5,50,Female,5_left.jpg,5_right.jpg,moderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",5_right.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6387,4686,63,Male,4686_left.jpg,4686_right.jpg,severe nonproliferative retinopathy,proliferative diabetic retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4686_left.jpg
6388,4688,42,Male,4688_left.jpg,4688_right.jpg,moderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4688_left.jpg
6389,4689,54,Male,4689_left.jpg,4689_right.jpg,mild nonproliferative retinopathy,normal fundus,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4689_left.jpg
6390,4690,57,Male,4690_left.jpg,4690_right.jpg,mild nonproliferative retinopathy,mild nonproliferative retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4690_left.jpg
6391,4784,58,Male,4784_left.jpg,4784_right.jpg,hypertensive retinopathy，age-related macular d...,hypertensive retinopathy，age-related macular d...,0,0,0,0,1,1,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['H'],"[0, 0, 0, 0, 0, 1, 0, 0]",4784_left.jpg

In [5]:
#renaming relou features
df = df.rename(columns = {'Left-Diagnostic Keywords' : 'Ldiag', 'Right-Diagnostic Keywords': 'Rdiag'})

In [6]:
df.columns

Index(['ID', 'Patient Age', 'Patient Sex', 'Left-Fundus', 'Right-Fundus',
       'Ldiag', 'Rdiag', 'N', 'D', 'G', 'C', 'A', 'H', 'M', 'O', 'filepath',
       'labels', 'target', 'filename'],
      dtype='object')

In [7]:
keywords= ['optic disk photographically invisible', 'lens dust']

df = df[df['Ldiag'].map(lambda x : all(kw not in x for kw in keywords))]

In [8]:
#                             [N, D, G, C, A, H, M, O]
dico_ds = {
    'normal'      : pd.Series([1, 0, 0, 0, 0, 0, 0, 0]),
    'retinopathy' : pd.Series([0, 1, 0, 0, 0, 0, 0, 0]),
    'glaucoma'    : pd.Series([0, 0, 1, 0, 0, 0, 0, 0]),
    'cataract'    : pd.Series([0, 0, 0, 1, 0, 0, 0, 0]),
    'age'         : pd.Series([0, 0, 0, 0, 1, 0, 0, 0]),
    'hypertensive': pd.Series([0, 0, 0, 0, 0, 1, 0, 0]),
    'myopi'       : pd.Series([0, 0, 0, 0, 0, 0, 1, 0])
}

In [9]:
def check_diag(word, feat):
    tmp_df = df[df[feat]==1][['Ldiag', 'Rdiag']]
    mask = tmp_df.apply(lambda x : word in x[0] or word in x[1] , axis = 1)
    print(f"We missed {len(tmp_df[-mask])} observations for {word}")

In [10]:
check_diag('normal', 'N')
check_diag('retinopathy', 'D')
check_diag('glaucoma', 'G')
check_diag('cataract', 'C')
check_diag('age', 'A')
check_diag('myopi', 'M')

We missed 0 observations for normal
We missed 0 observations for retinopathy
We missed 0 observations for glaucoma
We missed 0 observations for cataract
We missed 0 observations for age
We missed 0 observations for myopi

C:\Users\sruja\AppData\Local\Temp\ipykernel_3712\557008367.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mask = tmp_df.apply(lambda x : word in x[0] or word in x[1] , axis = 1)
C:\Users\sruja\AppData\Local\Temp\ipykernel_3712\557008367.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mask = tmp_df.apply(lambda x : word in x[0] or word in x[1] , axis = 1)
C:\Users\sruja\AppData\Local\Temp\ipykernel_3712\557008367.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mask = tmp_df.apply(lambda x : word in x[0] or word in x[1] , axis = 1)
C:\Users\sruja\AppData\Local\Temp\ipykernel_3712\557008367.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mask = tmp_df.apply(lambda x : word in x[0] or word in x[1] , axis = 1)
C:\Users\sruja\AppData\Local\Temp\ipykernel_3712\557008367.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mask = tmp_df.apply(lambda x : word in x[0] or word in x[1] , axis = 1)
C:\Users\sruja\AppData\Local\Temp\ipykernel_3712\557008367.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mask = tmp_df.apply(lambda x : word in x[0] or word in x[1] , axis = 1)

In [11]:
def create_target(diag, dico = dico_ds):
    res = np.zeros(8, dtype=int)
    for kw, series in dico.items():
        if kw in diag:
            res = res + series
    if res.sum() == 0:
        return [0, 0, 0, 0, 0, 0, 0, 1]
    else:
        return list(res)

df_right = df[['Rdiag', 'filename','target','Patient Age', 'Patient Sex']].rename(columns ={'Rdiag' : 'Diagnostic'})
df_left = df[['Ldiag', 'filename','target','Patient Age', 'Patient Sex']].rename(columns ={'Ldiag' : 'Diagnostic'})
df_all = pd.concat([df_right, df_left]).rename(columns ={'target' : 'target_init'})
df_all['Target']=df_all.Diagnostic.map(create_target)
df_all

,Diagnostic,filename,target_init,Patient Age,Patient Sex,Target
0,normal fundus,0_right.jpg,"[1, 0, 0, 0, 0, 0, 0, 0]",69,Female,"[1, 0, 0, 0, 0, 0, 0, 0]"
1,normal fundus,1_right.jpg,"[1, 0, 0, 0, 0, 0, 0, 0]",57,Male,"[1, 0, 0, 0, 0, 0, 0, 0]"
2,moderate non proliferative retinopathy,2_right.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",42,Male,"[0, 1, 0, 0, 0, 0, 0, 0]"
3,mild nonproliferative retinopathy,4_right.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",53,Male,"[0, 1, 0, 0, 0, 0, 0, 0]"
4,moderate non proliferative retinopathy,5_right.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",50,Female,"[0, 1, 0, 0, 0, 0, 0, 0]"
...,...,...,...,...,...,...
6387,severe nonproliferative retinopathy,4686_left.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",63,Male,"[0, 1, 0, 0, 0, 0, 0, 0]"
6388,moderate non proliferative retinopathy,4688_left.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",42,Male,"[0, 1, 0, 0, 0, 0, 0, 0]"
6389,mild nonproliferative retinopathy,4689_left.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",54,Male,"[0, 1, 0, 0, 0, 0, 0, 0]"
6390,mild nonproliferative retinopathy,4690_left.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",57,Male,"[0, 1, 0, 0, 0, 0, 0, 0]"
6391,hypertensive retinopathy，age-related macular d...,4784_left.jpg,"[0, 0, 0, 0, 0, 1, 0, 0]",58,Male,"[0, 1, 0, 0, 1, 1, 0, 0]"

In [12]:
pd.set_option('display.max_colwidth', None)
df_all[df_all.Target.map(lambda x : sum(x)>2)].head()

,Diagnostic,filename,target_init,Patient Age,Patient Sex,Target
276,wet age-related macular degeneration，hypertensive retinopathy,315_right.jpg,"[0, 0, 0, 0, 1, 0, 0, 0]",57,Female,"[0, 1, 0, 0, 1, 1, 0, 0]"
301,hypertensive retinopathy，cataract,345_right.jpg,"[0, 0, 0, 0, 0, 1, 0, 0]",64,Female,"[0, 1, 0, 1, 0, 1, 0, 0]"
319,hypertensive retinopathy，suspected glaucoma,365_right.jpg,"[0, 0, 0, 0, 0, 1, 0, 0]",60,Female,"[0, 1, 1, 0, 0, 1, 0, 0]"
856,dry age-related macular degeneration，hypertensive retinopathy,998_right.jpg,"[0, 0, 0, 0, 1, 0, 0, 0]",36,Male,"[0, 1, 0, 0, 1, 1, 0, 0]"
990,glaucoma，myopia retinopathy,1213_right.jpg,"[0, 0, 1, 0, 0, 0, 0, 0]",76,Male,"[0, 1, 1, 0, 0, 0, 1, 0]"

In [13]:
list_names =['N', 'D', 'G', 'C', 'A', 'H', 'M', 'O']

def list2str(l, list_names = list_names):
    res = ''
    for i, it in enumerate(l):
        if it :
            res=res+list_names[i]
    return res

df_all['tarstr'] = df_all.Target.map(list2str)

In [14]:

df_all.head(10)

,Diagnostic,filename,target_init,Patient Age,Patient Sex,Target,tarstr
0,normal fundus,0_right.jpg,"[1, 0, 0, 0, 0, 0, 0, 0]",69,Female,"[1, 0, 0, 0, 0, 0, 0, 0]",N
1,normal fundus,1_right.jpg,"[1, 0, 0, 0, 0, 0, 0, 0]",57,Male,"[1, 0, 0, 0, 0, 0, 0, 0]",N
2,moderate non proliferative retinopathy,2_right.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",42,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D
3,mild nonproliferative retinopathy,4_right.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",53,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D
4,moderate non proliferative retinopathy,5_right.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",50,Female,"[0, 1, 0, 0, 0, 0, 0, 0]",D
5,moderate non proliferative retinopathy，epiretinal membrane,6_right.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",60,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D
6,mild nonproliferative retinopathy,7_right.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",60,Female,"[0, 1, 0, 0, 0, 0, 0, 0]",D
7,normal fundus,8_right.jpg,"[1, 0, 0, 0, 0, 0, 0, 0]",59,Male,"[1, 0, 0, 0, 0, 0, 0, 0]",N
8,vitreous degeneration,9_right.jpg,"[0, 0, 0, 0, 0, 0, 0, 1]",54,Male,"[0, 0, 0, 0, 0, 0, 0, 1]",O
9,normal fundus,10_right.jpg,"[1, 0, 0, 0, 0, 0, 0, 0]",70,Male,"[1, 0, 0, 0, 0, 0, 0, 0]",N

In [15]:

for i,ds in enumerate(list_names):
    df_all[ds] = df_all.Target.map(lambda x : x[i])

In [16]:

df_all

,Diagnostic,filename,target_init,Patient Age,Patient Sex,Target,tarstr,N,D,G,C,A,H,M,O
0,normal fundus,0_right.jpg,"[1, 0, 0, 0, 0, 0, 0, 0]",69,Female,"[1, 0, 0, 0, 0, 0, 0, 0]",N,1,0,0,0,0,0,0,0
1,normal fundus,1_right.jpg,"[1, 0, 0, 0, 0, 0, 0, 0]",57,Male,"[1, 0, 0, 0, 0, 0, 0, 0]",N,1,0,0,0,0,0,0,0
2,moderate non proliferative retinopathy,2_right.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",42,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D,0,1,0,0,0,0,0,0
3,mild nonproliferative retinopathy,4_right.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",53,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D,0,1,0,0,0,0,0,0
4,moderate non proliferative retinopathy,5_right.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",50,Female,"[0, 1, 0, 0, 0, 0, 0, 0]",D,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6387,severe nonproliferative retinopathy,4686_left.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",63,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D,0,1,0,0,0,0,0,0
6388,moderate non proliferative retinopathy,4688_left.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",42,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D,0,1,0,0,0,0,0,0
6389,mild nonproliferative retinopathy,4689_left.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",54,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D,0,1,0,0,0,0,0,0
6390,mild nonproliferative retinopathy,4690_left.jpg,"[0, 1, 0, 0, 0, 0, 0, 0]",57,Male,"[0, 1, 0, 0, 0, 0, 0, 0]",D,0,1,0,0,0,0,0,0
6391,hypertensive retinopathy，age-related macular degeneration,4784_left.jpg,"[0, 0, 0, 0, 0, 1, 0, 0]",58,Male,"[0, 1, 0, 0, 1, 1, 0, 0]",DAH,0,1,0,0,1,1,0,0

In [17]:
df_all.to_csv('full_df_cleaned.csv',index = False)

In [18]:

df_all[df_all.filename=='305_right.jpg']

,Diagnostic,filename,target_init,Patient Age,Patient Sex,Target,tarstr,N,D,G,C,A,H,M,O
267,hypertensive retinopathy，macular epiretinal membrane,305_right.jpg,"[0, 0, 0, 0, 0, 1, 0, 0]",55,Male,"[0, 1, 0, 0, 0, 1, 0, 0]",DH,0,1,0,0,0,1,0,0
267,"hypertensive retinopathy,diabetic retinopathy",305_right.jpg,"[0, 0, 0, 0, 0, 1, 0, 0]",55,Male,"[0, 1, 0, 0, 0, 1, 0, 0]",DH,0,1,0,0,0,1,0,0